version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-vite-frontend
    ports:
      - "5173:80" # Mapeia a porta 80 do container Nginx para 5173 na sua máquina
    # O frontend depende que o backend esteja pronto para receber requisições.
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge